[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "bioimagenes"
version = "0.1.0"
description = "Librería para procesamiento, análisis y visualización de imágenes médicas"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [
    {name = "Brihan Venturelli"}
]
keywords = [ 
    "procesamiento de imágenes", 
    "imágenes médicas", 
    "tomografía", 
    "radiografía", 
    "termografía", 
    "ingeniería biomédica" 
] 
classifiers = [ 
    "Programming Language :: Python :: 3", 
    "Programming Language :: Python :: 3.10", 
    "License :: OSI Approved :: MIT License", 
    "Operating System :: OS Independent", 
    "Intended Audience :: Science/Research", 
    "Topic :: Scientific/Engineering :: Image Processing", 
    "Topic :: Scientific/Engineering :: Medical Science Apps." 
] 
dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "nibabel"
]

[project.optional-dependencies]
dev = [
    "pytest"
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]